<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>pl.tkaczyk</groupId>
    <artifactId>vigil-root-pom</artifactId>
    <version>0.0.1</version>
    <name>vigil-root-pom</name>
    <description>Root pom for Vigil App</description>
    <packaging>pom</packaging>
    <licenses>
        <license>
            <name>Apache License, Veriosn 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
        </license>
    </licenses>
    <developers>
        <developer>
            <name>patryktk</name>
        </developer>
    </developers>
    <scm>
        <url>https://github.com/patryktk/Vigil</url>
    </scm>

    <properties>
        <common-lib.version>0.1</common-lib.version>
        <java.version>25</java.version>
        <lombok.version>1.18.46</lombok.version>
        <spring-boot.version>4.0.6</spring-boot.version>
        <flyway.version>11.14.1</flyway.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <spring-cloud.version>2025.1.2</spring-cloud.version>
    </properties>
    <modules>
        <module>common</module>
        <module>scraper-service</module>
        <module>processor-service</module>
        <module>api-service</module>
        <module>sheets-service</module>
        <module>eureka-server</module>
        <module>config-server</module>
    </modules>

<!--    Tutaj dodaje biblioteki dla wszystkich modułów -->
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>annotationProcessor</scope>
            <version>${lombok.version}</version>
        </dependency>
    </dependencies>

<!--    Tutaj tylko rejestruje wersje danych bibliotek-->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <scope>annotationProcessor</scope>
                <version>${lombok.version}</version>
            </dependency>
            <dependency>
                <groupId>pl.tkaczyk</groupId>
                <artifactId>common</artifactId>
                <version>${common-lib.version}</version>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-bom</artifactId>
                <version>2.0.5</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring-boot.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <release>${java.version}</release>

                        <annotationProcessorPaths>

                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>


                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>