CREATE TABLE company
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    created_by   VARCHAR(255),
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_by   VARCHAR(255),
    company_name VARCHAR(255),
    ticker       VARCHAR(255),
    CONSTRAINT pk_company PRIMARY KEY (id)
);

CREATE TABLE dividend_announcement
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_by         VARCHAR(255),
    company_id         BIGINT,
    last_date_to_buy   date,
    dividend_yield_pct DECIMAL,
    amount_price       DECIMAL,
    pay_date           date,
    CONSTRAINT pk_dividendannouncement PRIMARY KEY (id)
);

CREATE TABLE stock_snapshot
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                    TIMESTAMP WITHOUT TIME ZONE,
    created_by                    VARCHAR(255),
    updated_at                    TIMESTAMP WITHOUT TIME ZONE,
    updated_by                    VARCHAR(255),
    company_id                    BIGINT NOT NULL,
    price                         DECIMAL,
    price_to_earnings             DECIMAL,
    price_to_book_value           DECIMAL,
    price_to_sales                DECIMAL,
    price_to_operating_income     DECIMAL,
    ev_to_sales                   DECIMAL,
    ev_to_ebit                    DECIMAL,
    ev_to_ebitda                  DECIMAL,
    earnings_per_share            DECIMAL,
    total_debt                    DECIMAL,
    net_debt                      DECIMAL,
    net_financial_debt            DECIMAL,
    debt_to_equity                DECIMAL,
    net_debt_to_ebitda            DECIMAL,
    return_on_equity_pct          DECIMAL,
    return_on_assets_pct          DECIMAL,
    operating_margin_pct          DECIMAL,
    net_profit_margin_pct         DECIMAL,
    sales_margin_pct              DECIMAL,
    current_ratio                 DECIMAL,
    revenue                       DECIMAL,
    gross_profit                  DECIMAL,
    ebit                          DECIMAL,
    net_income                    DECIMAL,
    depreciation_and_amortization DECIMAL,
    equity                        DECIMAL,
    CONSTRAINT pk_stocksnapshot PRIMARY KEY (id)
);

ALTER TABLE dividend_announcement
    ADD CONSTRAINT FK_DIVIDENDANNOUNCEMENT_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE stock_snapshot
    ADD CONSTRAINT FK_STOCKSNAPSHOT_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);