CREATE TABLE company
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    created_by   VARCHAR(255),
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_by   VARCHAR(255),
    company_name VARCHAR(255),
    CONSTRAINT pk_company PRIMARY KEY (id)
);

CREATE TABLE dividend_announcement
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    created_by           VARCHAR(255),
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_by           VARCHAR(255),
    company_id           BIGINT,
    date_of_announcement date,
    CONSTRAINT pk_dividendannouncement PRIMARY KEY (id)
);

CREATE TABLE stock_snapshot
(
    id                                             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                                     TIMESTAMP WITHOUT TIME ZONE,
    created_by                                     VARCHAR(255),
    updated_at                                     TIMESTAMP WITHOUT TIME ZONE,
    updated_by                                     VARCHAR(255),
    company_id                                     BIGINT,
    share_price                                    VARCHAR(255),
    price_to_earnings_ratio                        VARCHAR(255),
    price_to_book_value_ratio                      VARCHAR(255),
    price_to_sales_ratio                           VARCHAR(255),
    earnings_per_share                             VARCHAR(255),
    price_to_operating_income_ratio                VARCHAR(255),
    enterprise_value_to_sales_ratio                VARCHAR(255),
    enterprise_value_to_ebit_ratio                 VARCHAR(255),
    enterprise_value_to_ebitda_ratio               VARCHAR(255),
    total_debt                                     VARCHAR(255),
    debt_to_equity_ratio                           VARCHAR(255),
    net_debt                                       VARCHAR(255),
    net_debt_to_ebitda_ratio                       VARCHAR(255),
    net_financial_debt                             VARCHAR(255),
    equity                                         VARCHAR(255),
    roe                                            VARCHAR(255),
    roa                                            VARCHAR(255),
    operating_profit_margin                        VARCHAR(255),
    net_profit_margin                              VARCHAR(255),
    sales_profit_margin                            VARCHAR(255),
    roic                                           VARCHAR(255),
    current_ratio                                  VARCHAR(255),
    sales_revenue                                  VARCHAR(255),
    gross_profit                                   VARCHAR(255),
    ebit                                           VARCHAR(255),
    depreciation                                   VARCHAR(255),
    net_profit                                     VARCHAR(255),
    ebit_margin                                    VARCHAR(255),
    earnings_per_share_three_year_growth           VARCHAR(255),
    earnings_per_share_quarter_over_quarter_growth VARCHAR(255),
    sales_revenue_quarter_over_quarter_growth      VARCHAR(255),
    net_profit_quarter_over_quarter_growth         VARCHAR(255),
    ebitda                                         VARCHAR(255),
    ebitda_margin                                  VARCHAR(255),
    peg                                            VARCHAR(255),
    sma50                                          VARCHAR(255),
    sma200                                         VARCHAR(255),
    momentum                                       VARCHAR(255),
    rsi                                            VARCHAR(255),
    CONSTRAINT pk_stocksnapshot PRIMARY KEY (id)
);

ALTER TABLE dividend_announcement
    ADD CONSTRAINT FK_DIVIDENDANNOUNCEMENT_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE stock_snapshot
    ADD CONSTRAINT FK_STOCKSNAPSHOT_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);