server:
  port: 8030


spring:
  application:
    name: scraper-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true


resilience4j:
  retry:
    instances:
      jsoup:
        max-attempts: 3
        wait-duration:
          seconds: 1
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions: #Defines on which exceptions do retry if defined don't need to define ignore-exceptions
          - pl.tkaczyk.scraperservice.exception.HtmlFetchException
    retry-aspect-order: 2
  ratelimiter:
    instances:
      jsoup:
        limit-for-period: 2 #Allow 2 attempts
        limit-refresh-period: #In period of 1 second
          seconds: 1
        timeout-duration: #If off limit thread waits 5 seconds
          seconds: 5
    rate-limiter-aspect-order: 1
  circuitbreaker:
    instances:
      jsoup:
        sliding-window-size: 10 #how many request it has to monitor before it changes from closed to open CB
        permitted-number-of-calls-in-half-open-state: 2 #when in half-open status it allows 2 requests
        failure-rate-threshold: 50 #50% of request is failed move from closed -> open
        wait-duration-in-open-state: #how long before it moves to half-open from open
          seconds: 30
        minimum-number-of-calls: 10 #CB starts raiting after 10 calls
    circuit-breaker-aspect-order: 3