server:
  port: 8030

spring:
  application:
    name: scraper-service
  datasource:
    url: jdbc:postgresql://localhost:5432/vigil-db #${DB_URL}
    username: ptnaza #${DB_USERNAME}
    password: ptnaza #${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    validate-on-migrate: true
  kafka:
    bootstrap-servers: localhost:29092 #kafka:9092

resilience4j:
  retry:
    instances:
      jsoup:
        max-attempts: 3
        wait-duration:
          seconds: 1
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions: #Defines on which exceptions do retry if defined don't need to define ignore-exceptions
          - pl.tkaczyk.scraperservice.exception.HtmlFetchException
      sheetsService:
        max-attempts: 3
        wait-duration:
          seconds: 1
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - feign.FeignException
    retry-aspect-order: 2
  ratelimiter:
    instances:
      jsoup:
        limit-for-period: 2 #Allow 2 attempts
        limit-refresh-period: #In period of 1 second
          seconds: 1
        timeout-duration: #If off limit thread waits 5 seconds
          seconds: 5
    rate-limiter-aspect-order: 1
  circuitbreaker:
    instances:
      jsoup:
        sliding-window-size: 10 #how many request it has to monitor before it changes from closed to open CB
        permitted-number-of-calls-in-half-open-state: 2 #when in half-open status it allows 2 requests
        failure-rate-threshold: 50 #50% of request is failed move from closed -> open
        wait-duration-in-open-state: #how long before it moves to half-open from open
          seconds: 30
        minimum-number-of-calls: 10 #CB starts raiting after 10 calls
      sheets-service:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 30
        minimum-number-of-calls: 5
    circuit-breaker-aspect-order: 3

logging:
  level:
    org.flywaydb: DEBUG

sheets-service:
  url: localhost:8040